### ISSUE TITLE
More Answer Buttons for ALL Cards

### ISSUE THREAD

**Issue by omega3** [steveaw/anki_addons#2]
Can you please create, based upon "More Answer Buttons for New Cards", a new add-on that that would work with old cards (that are already in review). I have some cards that have some non-sense (to me of course) due schedule and using edit, menu, reschedule for single cards is not very convenient. Unfortunately playing with interval modifier isn't a solution because it affects all cards.  

Edit:
I have just found "Quick reschedule in reviewer" add-on
https://ankiweb.net/shared/info/1190809692

But if you found my idea useful you can do it. 

Actually I was looking for a solution because I have some cards that a due 4 years from now, which I feel is a little exaggeration but I don't want to change interval modifier for the entire deck. On the other hand I am afraid that limiting maximum interval to certain number of days can cause a stockpile of reviews in a certain period of time in the future. I wonder if it is possible to create additional buttons that would be based on different interval modifier than the entire deck.

**Comment by ankitest** [comment]
@omega3 You can try to use: [~ More Answer Buttons for ALL Cards](https://ankiweb.net/shared/info/755044381)

No answer will be given, just apply additional interval.
SWAP_TAG may be assigned.

**Comment by omega3** [comment]
This one looks promising but I get errors 

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/usr/share/anki/aqt/webview.py", line 21, in link
    self._linkHandler(unicode(str))
  File "/home/omega3/Anki/addons/play_button.py", line 60, in review_link_handler_wrapper
    original_review_link_handler(reviewer, url)
  File "/usr/share/anki/aqt/reviewer.py", line 323, in _linkHandler
    self._answerCard(int(url[4:]))
  File "/usr/share/anki/anki/hooks.py", line 61, in repl
    return new(_old=old, _args, *_kwargs)
  File "/home/omega3/Anki/addons/_More_Answer_Buttons_for_ALL_Cards.py", line 133, in answer_card_intercepting
    if SWAP_TAG:
UnboundLocalError: local variable 'SWAP_TAG' referenced before assignment

So I removed play_button.py which is 
https://ankiweb.net/shared/info/498789867
Replay buttons on card

(but eventually I don't want to remove it because it is very usefull) but the next error ocured

Traceback (most recent call last):
  File "/usr/share/anki/aqt/webview.py", line 21, in link
    self._linkHandler(unicode(str))
  File "/usr/share/anki/aqt/reviewer.py", line 323, in _linkHandler
    self._answerCard(int(url[4:]))
  File "/usr/share/anki/anki/hooks.py", line 61, in repl
    return new(_old=old, _args, *_kwargs)
  File "/home/omega3/Anki/addons/_More_Answer_Buttons_for_ALL_Cards.py", line 133, in answer_card_intercepting
    if SWAP_TAG:
UnboundLocalError: local variable 'SWAP_TAG' referenced before assignment

reviewer.py I beleive is "Quick reschedule in reviewer" add-on
https://ankiweb.net/shared/info/1190809692

I deleted "Quick reschedule in reviewer" but still there is error

Traceback (most recent call last):
  File "/usr/share/anki/aqt/webview.py", line 21, in link
    self._linkHandler(unicode(str))
  File "/usr/share/anki/aqt/reviewer.py", line 323, in _linkHandler
    self._answerCard(int(url[4:]))
  File "/usr/share/anki/anki/hooks.py", line 61, in repl
    return new(_old=old, _args, *_kwargs)
  File "/home/omega3/Anki/addons/_More_Answer_Buttons_for_ALL_Cards.py", line 133, in answer_card_intercepting
    if SWAP_TAG:
UnboundLocalError: local variable 'SWAP_TAG' referenced before assignment

**Comment by ankitest** [comment]
Fixed.

**Comment by omega3** [comment]
Now it doesn't show additional buttons (even when I disable all other add-ons). Only 4 normal buttons are available for answer. 
But it doesn't show any errors.

Edit:
I checked on other deck -  with new cards it shows additional buttons. 

So only with old cards doesn't show.

**Comment by ankitest** [comment]
God knows what are you doing with this add-on. 
You can try to create new empty base folder on a flash card 
and play with this addon in it.

**Comment by omega3** [comment]
> God knows what are you doing with this add-on.

Hmm. Really nothing unusual:
old card
http://i.imgur.com/IS91ixE.jpg
new card
http://i.imgur.com/qO1e94p.jpg

**Comment by ankitest** [comment]
Let's go home.
https://github.com/ankitest/anki-musthave-addons-by-ankitest/issues/18

**Comment by omega3** [comment]
I am not sure I understand correctly but I copied code from Anki (edit option in anki) and pasted to that site
http://i.imgur.com/zlko4S3.jpg
http://i.imgur.com/XYC6Lu5.jpg
http://i.imgur.com/r0l5THW.jpg
I have made no changes to the code - only copy - paste.

Anki Version 2.0.36
Qt 4.8.6 PyQt 4.10.4

**Comment by ankitest** [comment]
Why don't you answer on my Github page? Once again:
https://github.com/ankitest/anki-musthave-addons-by-ankitest/issues/18

Screenshots shows clearly: you are running **More Answer Buttons for New Cards** 
which one can't serve extra buttons on young and mature cards. 
You should remove _More Answer Buttons for New Cards_ 
and reinstall **~ More Answer Buttons for ALL Cards**
then we can continue talking... on my Github page about my version of add-on.  
I don't understand why should I waste my time and effort on such obvious things

**Comment by omega3** [comment]
I am really sorry for that stupid mistake and wasting your time. Actually when I reported errors I had "More Answer Buttons for ALL Cards" but later I messed up. 

Of course now it works ok, even with all the other add-ons. 

Thank you very much for this add-on.
